---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: catalog
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/container-training-fleet/componentcatalog4flux.git
